---
- name: Install PostgreSQL
  yum: name=postgresql-server state=present

- name: Install Python adapter for PostgreSQL
  yum: name=python-psycopg2 state=present

- name: Initialize PostgreSQL Cluster
  command: postgresql-setup initdb creates=/var/lib/pgsql/data/postgresql.conf

- name: Enable PostgreSQL
  service: name=postgresql enabled=yes state=started

- name: Create database
  postgresql_db: name={{ dbname }}
  sudo: yes
  sudo_user: postgres

- name: Create user with access to database
  postgresql_user: db={{ dbname }} name={{ dbuser }} password={{ dbpassword }} priv=ALL
  sudo: yes
  sudo_user: postgres

- name: Set dbuser privileges
  postgresql_user: name={{ dbuser }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  sudo: yes
  sudo_user: postgres